### PR TITLE
Added a config file for affiliates to be used in the iframes in order to be passed to Shopify

### PR DESCRIPTION
**Pull request by xto**
Added a global config file that affiliates can modify to set their affiliate code and get referrals. 

It is left blank on purpose to avoid someone creating a affiliate code with the dummy value and profiting

Review @lreeves @minasmart 

CC @michael-thorpe @danielpatricio

### CODE REVIEW

**Comment by xto** [comment]
Pinging @richgilbank @harismahmood89 for reviews

**Comment by xto** [comment]
Looping in @fmouvet

**Comment by lreeves** [comment]
Sorry I missed this, looks good. Is the escaping of the affiliate code handled somewhere in apply_filters?

**Comment by xto** [comment]
@lreeves there's no escaping on the plugin side, but there is some in core

**Comment by richgilbank** [comment]
It _seems_ simple enough. :+1:

**Comment by fmouvet** [comment]
are we good to 🚢  this?

**Pull request merged**
